"""
Safety Engine — FHIR-Native Patient Safety Checks
===================================================
Evaluates contrast_rules (imaging) and ir_lab_thresholds/ir_med_holds (IR)
against patient data from FHIR resources.

Supports DUAL MODE:
  - Synthetic Mode (demo): Extracts safety data from text via LLM
  - Live Mode (production): Pulls from Epic/Cerner FHIR R4 endpoints

The engine returns a SafetyProfile: a list of flags, holds, and 
pre-medication requirements that are displayed alongside the Draft Protocol.
"""

import json
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from dataclasses import dataclass, field, asdict
from enum import Enum


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    HARD_STOP = "hard_stop"


class DataSource(str, Enum):
    SYNTHETIC = "synthetic"
    FHIR_LIVE = "fhir_live"


@dataclass
class SafetyFlag:
    """A single safety alert generated by rule evaluation."""
    rule_type: str              # e.g., "egfr_check", "allergy_check"
    severity: str               # "info", "warning", "hard_stop"
    message: str                # Human-readable alert
    triggered: bool             # Whether the rule was actually triggered
    action: str                 # "flag", "require_premedication", "substitute_protocol", etc.
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class MedHoldAlert:
    """An anticoagulation/antiplatelet hold requirement."""
    medication_name: str
    medication_class: str
    hold_hours_before: int
    resume_hours_after: Optional[int]
    patient_is_taking: bool         # Whether we detected this med in patient data
    renal_adjusted: bool = False    # Whether hold was adjusted for renal function
    adjusted_hold_hours: Optional[int] = None
    bridging_required: bool = False
    bridging_protocol: Optional[str] = None
    sir_reference: Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass 
class LabCheckResult:
    """Result of checking a specific lab value against a threshold."""
    lab_name: str
    required_operator: str
    required_value: float
    patient_value: Optional[float]
    patient_result_date: Optional[str]
    is_met: bool                    # Whether the lab meets the threshold
    is_stale: bool                  # Whether the result is too old
    action_if_not_met: str
    correction_guidance: Optional[str]
    sir_reference: Optional[str]

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class SafetyProfile:
    """
    Complete safety evaluation for a patient + protocol combination.
    This is what gets displayed in the "Draft Protocol" output.
    """
    data_source: str                          # "synthetic" or "fhir_live"
    overall_status: str = "clear"             # "clear", "warnings", "hard_stop"
    safety_flags: List[SafetyFlag] = field(default_factory=list)
    lab_checks: List[LabCheckResult] = field(default_factory=list)
    med_holds: List[MedHoldAlert] = field(default_factory=list)
    premedication_required: bool = False
    premedication_text: Optional[str] = None
    substitute_protocol_id: Optional[str] = None
    
    def to_dict(self) -> dict:
        return {
            "data_source": self.data_source,
            "overall_status": self.overall_status,
            "safety_flags": [f.to_dict() for f in self.safety_flags],
            "lab_checks": [l.to_dict() for l in self.lab_checks],
            "med_holds": [m.to_dict() for m in self.med_holds],
            "premedication_required": self.premedication_required,
            "premedication_text": self.premedication_text,
            "substitute_protocol_id": self.substitute_protocol_id,
        }

    def compute_overall_status(self):
        """Set overall_status based on the worst flag/lab/hold severity."""
        if any(f.triggered and f.severity == "hard_stop" for f in self.safety_flags):
            self.overall_status = "hard_stop"
        elif any(not lc.is_met and lc.action_if_not_met == "hard_stop" for lc in self.lab_checks):
            self.overall_status = "hard_stop"
        elif any(f.triggered for f in self.safety_flags) or any(not lc.is_met for lc in self.lab_checks):
            self.overall_status = "warnings"
        else:
            self.overall_status = "clear"


# ─────────────────────────────────────────────
# FHIR Patient Data Extraction
# ─────────────────────────────────────────────

def extract_patient_safety_data(fhir_bundle: dict) -> Dict[str, Any]:
    """
    Extract safety-relevant fields from a FHIR Bundle.
    Works with both synthetic bundles (from fhir_converter.py) and 
    real FHIR R4 bundles (from Epic/Cerner).
    
    Returns a standardized dict:
    {
        "sex": "female",
        "age": 34,
        "egfr": {"value": 65.0, "date": "2026-05-10"},
        "inr": {"value": 1.2, "date": "2026-05-14"},
        "platelets": {"value": 180000, "date": "2026-05-14"},
        "hgb": {"value": 12.5, "date": "2026-05-14"},
        "fibrinogen": {"value": 350.0, "date": "2026-05-14"},
        "hcg": {"value": "negative", "date": "2026-05-14"},
        "allergies": ["Omnipaque", "iodinated contrast"],
        "medications": ["Apixaban", "Aspirin"],
    }
    """
    data = {
        "sex": None,
        "age": None,
        "egfr": None,
        "inr": None,
        "platelets": None,
        "hgb": None,
        "fibrinogen": None,
        "hcg": None,
        "allergies": [],
        "medications": [],
    }
    
    entries = fhir_bundle.get("entry", [])
    
    for entry in entries:
        resource = entry.get("resource", {})
        rtype = resource.get("resourceType")
        
        if rtype == "Patient":
            data["sex"] = resource.get("gender")
            # Age from birthDate if available
            birth_date = resource.get("birthDate")
            if birth_date:
                try:
                    bd = datetime.strptime(birth_date[:10], "%Y-%m-%d")
                    data["age"] = (datetime.now() - bd).days // 365
                except (ValueError, TypeError):
                    pass
        
        elif rtype == "Observation":
            _extract_observation(resource, data)
        
        elif rtype == "AllergyIntolerance":
            _extract_allergy(resource, data)
        
        elif rtype in ("MedicationStatement", "MedicationRequest", "MedicationAdministration"):
            _extract_medication(resource, data)
    
    return data


def _extract_observation(resource: dict, data: dict):
    """Parse an Observation resource for lab values."""
    code_text = ""
    codings = resource.get("code", {}).get("coding", [])
    for coding in codings:
        code_text += coding.get("display", "") + " " + coding.get("code", "") + " "
    code_text += resource.get("code", {}).get("text", "")
    code_text = code_text.lower()
    
    value = None
    value_quantity = resource.get("valueQuantity", {})
    if value_quantity:
        value = value_quantity.get("value")
    elif resource.get("valueString"):
        value = resource.get("valueString")
    
    date = resource.get("effectiveDateTime", resource.get("issued", ""))
    if isinstance(date, str):
        date = date[:10]  # Keep just the date portion
    
    lab_entry = {"value": value, "date": date} if value is not None else None
    
    # Map to our standardized keys
    if any(term in code_text for term in ["egfr", "gfr", "glomerular"]):
        data["egfr"] = lab_entry
    elif any(term in code_text for term in ["inr", "6301-6"]):
        data["inr"] = lab_entry
    elif any(term in code_text for term in ["platelet", "777-3", "plt"]):
        data["platelets"] = lab_entry
    elif any(term in code_text for term in ["hemoglobin", "hgb", "718-7"]):
        data["hgb"] = lab_entry
    elif any(term in code_text for term in ["fibrinogen", "3255-7"]):
        data["fibrinogen"] = lab_entry
    elif any(term in code_text for term in ["hcg", "pregnancy", "beta-hcg"]):
        data["hcg"] = lab_entry


def _extract_allergy(resource: dict, data: dict):
    """Parse an AllergyIntolerance resource for contrast agent allergies."""
    code = resource.get("code", {})
    text = code.get("text", "")
    if text:
        data["allergies"].append(text)
    for coding in code.get("coding", []):
        display = coding.get("display", "")
        if display and display not in data["allergies"]:
            data["allergies"].append(display)


def _extract_medication(resource: dict, data: dict):
    """Parse medication resources for anticoagulant/antiplatelet detection.
    Handles both R4 (medicationCodeableConcept) and R5 (medication.concept) formats.
    """
    med_code = None
    
    # R4 format: medicationCodeableConcept
    if "medicationCodeableConcept" in resource:
        med_code = resource["medicationCodeableConcept"]
    # R5 format: medication.concept (CodeableReference)
    elif "medication" in resource:
        med_ref = resource["medication"]
        if isinstance(med_ref, dict):
            med_code = med_ref.get("concept", med_ref)
    # Fallback: medicationReference
    elif "medicationReference" in resource:
        med_code = resource["medicationReference"]
    
    if isinstance(med_code, dict):
        text = med_code.get("text", "")
        if text:
            data["medications"].append(text)
        for coding in med_code.get("coding", []):
            display = coding.get("display", "")
            if display and display not in data["medications"]:
                data["medications"].append(display)


# ─────────────────────────────────────────────
# Rule Evaluation Engine
# ─────────────────────────────────────────────

def evaluate_contrast_rules(
    contrast_rules: List[Dict[str, Any]],
    patient_data: Dict[str, Any]
) -> List[SafetyFlag]:
    """
    Evaluate a list of contrast_rule rows against extracted patient data.
    Returns a list of SafetyFlag objects (triggered and untriggered).
    """
    flags = []
    
    for rule in contrast_rules:
        rule_type = rule["rule_type"]
        condition = rule.get("condition_json", {})
        if isinstance(condition, str):
            condition = json.loads(condition)
        
        triggered = False
        details = {}
        
        if rule_type == "egfr_check":
            triggered, details = _check_egfr(condition, patient_data)
        elif rule_type == "allergy_check":
            triggered, details = _check_allergies(condition, patient_data)
        elif rule_type == "pregnancy_check":
            triggered, details = _check_pregnancy(condition, patient_data)
        elif rule_type == "bmi_check":
            triggered, details = _check_bmi(condition, patient_data)
        
        flag = SafetyFlag(
            rule_type=rule_type,
            severity=rule.get("severity", "warning"),
            message=rule["alert_message"] if triggered else f"✅ {rule_type} — Passed",
            triggered=triggered,
            action=rule["action_if_triggered"],
            details=details,
        )
        
        # Attach premedication or substitute info if triggered
        if triggered:
            if rule.get("premedication_text"):
                flag.details["premedication_text"] = rule["premedication_text"]
            if rule.get("substitute_protocol_id"):
                flag.details["substitute_protocol_id"] = rule["substitute_protocol_id"]
        
        flags.append(flag)
    
    return flags


def _check_egfr(condition: dict, patient_data: dict) -> tuple:
    """Check if patient's eGFR meets the minimum threshold."""
    egfr_data = patient_data.get("egfr")
    min_egfr = condition.get("egfr_min", 30)
    max_age_days = condition.get("max_age_days", 90)
    
    if not egfr_data or egfr_data.get("value") is None:
        return False, {"status": "no_data", "note": "No eGFR on file — manual check required"}
    
    value = egfr_data["value"]
    details = {"patient_egfr": value, "threshold": min_egfr}
    
    # Check staleness
    if egfr_data.get("date"):
        try:
            result_date = datetime.strptime(str(egfr_data["date"])[:10], "%Y-%m-%d")
            age_days = (datetime.now() - result_date).days
            details["result_age_days"] = age_days
            if age_days > max_age_days:
                details["stale"] = True
                details["note"] = f"eGFR result is {age_days} days old (max allowed: {max_age_days})"
        except (ValueError, TypeError):
            pass
    
    triggered = isinstance(value, (int, float)) and value < min_egfr
    return triggered, details


def _check_allergies(condition: dict, patient_data: dict) -> tuple:
    """Check if patient has allergies to specified contrast agents."""
    agents = condition.get("agents", [])
    patient_allergies = [a.lower() for a in patient_data.get("allergies", [])]
    
    matches = []
    for agent in agents:
        for allergy in patient_allergies:
            if agent.lower() in allergy or allergy in agent.lower():
                matches.append({"agent": agent, "patient_allergy": allergy})
    
    triggered = len(matches) > 0
    details = {"matched_allergies": matches} if triggered else {"status": "no_allergy_match"}
    return triggered, details


def _check_pregnancy(condition: dict, patient_data: dict) -> tuple:
    """Check pregnancy risk for females of childbearing age."""
    sex = patient_data.get("sex", "").lower()
    age = patient_data.get("age")
    
    required_sex = condition.get("sex", "female").lower()
    age_min = condition.get("age_min", 12)
    age_max = condition.get("age_max", 55)
    
    if sex != required_sex:
        return False, {"status": "not_applicable", "reason": f"Patient sex: {sex}"}
    
    if age is not None and (age < age_min or age > age_max):
        return False, {"status": "not_applicable", "reason": f"Patient age {age} outside {age_min}-{age_max}"}
    
    # If female of childbearing age, check HCG
    hcg = patient_data.get("hcg")
    details = {"sex": sex, "age": age}
    
    if not hcg or hcg.get("value") is None:
        details["hcg_status"] = "not_available"
        details["note"] = "β-HCG not on file — must verify pregnancy status before proceeding"
        return True, details
    
    hcg_value = hcg["value"]
    if isinstance(hcg_value, str):
        if "negative" in hcg_value.lower() or "not pregnant" in hcg_value.lower():
            details["hcg_status"] = "negative"
            return False, details
        elif "positive" in hcg_value.lower() or "pregnant" in hcg_value.lower():
            details["hcg_status"] = "positive"
            return True, details
    elif isinstance(hcg_value, (int, float)):
        if hcg_value < 5:  # <5 mIU/mL is negative
            details["hcg_status"] = "negative"
            details["hcg_value"] = hcg_value
            return False, details
        else:
            details["hcg_status"] = "positive"
            details["hcg_value"] = hcg_value
            return True, details
    
    details["hcg_status"] = "indeterminate"
    return True, details


def _check_bmi(condition: dict, patient_data: dict) -> tuple:
    """Check BMI-related conditions (e.g., oral contrast conditional)."""
    bmi = patient_data.get("bmi")
    if bmi is None:
        return False, {"status": "no_data"}
    
    if "bmi_lt" in condition and bmi < condition["bmi_lt"]:
        return True, {"patient_bmi": bmi, "threshold": condition["bmi_lt"]}
    if "bmi_gt" in condition and bmi > condition["bmi_gt"]:
        return True, {"patient_bmi": bmi, "threshold": condition["bmi_gt"]}
    
    return False, {"patient_bmi": bmi}


def evaluate_ir_lab_thresholds(
    lab_thresholds: List[Dict[str, Any]],
    patient_data: Dict[str, Any]
) -> List[LabCheckResult]:
    """
    Evaluate IR lab threshold rules against patient lab data.
    """
    results = []
    
    lab_key_map = {
        "INR": "inr",
        "Platelets": "platelets",
        "Hgb": "hgb",
        "Fibrinogen": "fibrinogen",
    }
    
    for thresh in lab_thresholds:
        lab_name = thresh["lab_name"]
        patient_key = lab_key_map.get(lab_name, lab_name.lower())
        patient_lab = patient_data.get(patient_key)
        
        patient_value = None
        patient_date = None
        is_stale = False
        
        if patient_lab and patient_lab.get("value") is not None:
            patient_value = patient_lab["value"]
            patient_date = patient_lab.get("date")
            
            # Check staleness
            max_hours = thresh.get("max_result_age_hours", 72)
            if patient_date:
                try:
                    rd = datetime.strptime(str(patient_date)[:10], "%Y-%m-%d")
                    age_hours = (datetime.now() - rd).total_seconds() / 3600
                    is_stale = age_hours > max_hours
                except (ValueError, TypeError):
                    pass
        
        # Evaluate threshold
        is_met = False
        if patient_value is not None and isinstance(patient_value, (int, float)):
            op = thresh["threshold_operator"]
            tv = thresh["threshold_value"]
            tvu = thresh.get("threshold_value_upper")
            
            if op == "<=":
                is_met = patient_value <= tv
            elif op == ">=":
                is_met = patient_value >= tv
            elif op == "<":
                is_met = patient_value < tv
            elif op == ">":
                is_met = patient_value > tv
            elif op == "between" and tvu is not None:
                is_met = tv <= patient_value <= tvu
            elif op == "==":
                is_met = patient_value == tv
        
        # If stale, treat as not met
        if is_stale:
            is_met = False
        
        results.append(LabCheckResult(
            lab_name=lab_name,
            required_operator=thresh["threshold_operator"],
            required_value=thresh["threshold_value"],
            patient_value=patient_value,
            patient_result_date=patient_date,
            is_met=is_met,
            is_stale=is_stale,
            action_if_not_met=thresh.get("action_if_not_met", "flag"),
            correction_guidance=thresh.get("correction_guidance"),
            sir_reference=thresh.get("sir_reference"),
        ))
    
    return results


def evaluate_ir_med_holds(
    med_holds: List[Dict[str, Any]],
    patient_data: Dict[str, Any]
) -> List[MedHoldAlert]:
    """
    Check patient's medications against IR hold requirements.
    Adjusts hold times for renal function if applicable.
    """
    patient_meds = [m.lower() for m in patient_data.get("medications", [])]
    egfr_data = patient_data.get("egfr")
    egfr_value = egfr_data.get("value") if egfr_data else None
    
    alerts = []
    
    for hold in med_holds:
        med_name = hold["medication_name"]
        
        # Check if patient is on this medication
        # Match by generic name, brand name, or partial match
        is_taking = False
        search_terms = med_name.lower().replace("(", "").replace(")", "").split()
        for patient_med in patient_meds:
            if any(term in patient_med for term in search_terms if len(term) > 3):
                is_taking = True
                break
        
        hold_hours = hold["hold_hours_before"]
        renal_adjusted = False
        adjusted_hours = None
        
        # Adjust for renal function if applicable
        renal_adj = hold.get("renal_adjustment")
        if renal_adj and egfr_value is not None:
            if isinstance(renal_adj, str):
                renal_adj = json.loads(renal_adj)
            
            if egfr_value < 30 and "egfr_lt_30" in renal_adj:
                adjusted_hours = renal_adj["egfr_lt_30"].get("hold_hours_before", hold_hours)
                renal_adjusted = True
            elif 30 <= egfr_value < 50 and "egfr_30_50" in renal_adj:
                adjusted_hours = renal_adj["egfr_30_50"].get("hold_hours_before", hold_hours)
                renal_adjusted = True
        
        alerts.append(MedHoldAlert(
            medication_name=med_name,
            medication_class=hold.get("medication_class", ""),
            hold_hours_before=hold_hours,
            resume_hours_after=hold.get("resume_hours_after"),
            patient_is_taking=is_taking,
            renal_adjusted=renal_adjusted,
            adjusted_hold_hours=adjusted_hours,
            bridging_required=hold.get("bridging_required", False),
            bridging_protocol=hold.get("bridging_protocol"),
            sir_reference=hold.get("sir_reference"),
        ))
    
    return alerts


# ─────────────────────────────────────────────
# Top-Level Evaluation
# ─────────────────────────────────────────────

def evaluate_safety(
    protocol_data: Dict[str, Any],
    patient_data: Dict[str, Any],
    data_source: str = "synthetic"
) -> SafetyProfile:
    """
    Run all safety checks for a given protocol + patient combination.
    
    Args:
        protocol_data: Full protocol dict including contrast_rules, 
                       ir_details with lab_thresholds and med_holds.
        patient_data: Standardized patient dict from extract_patient_safety_data().
        data_source: "synthetic" or "fhir_live"
    
    Returns:
        SafetyProfile with all flags, lab checks, and med hold alerts.
    """
    profile = SafetyProfile(data_source=data_source)
    
    # 1. Contrast / imaging safety rules
    contrast_rules = protocol_data.get("contrast_rules", [])
    if contrast_rules:
        profile.safety_flags = evaluate_contrast_rules(contrast_rules, patient_data)
        
        # Check for premedication requirement
        for flag in profile.safety_flags:
            if flag.triggered and flag.action == "require_premedication":
                profile.premedication_required = True
                profile.premedication_text = flag.details.get("premedication_text")
            if flag.triggered and flag.action == "substitute_protocol":
                profile.substitute_protocol_id = flag.details.get("substitute_protocol_id")
    
    # 2. IR lab thresholds
    ir_details = protocol_data.get("ir_details", {})
    lab_thresholds = ir_details.get("lab_thresholds", [])
    if lab_thresholds:
        profile.lab_checks = evaluate_ir_lab_thresholds(lab_thresholds, patient_data)
    
    # 3. IR medication holds
    med_holds = ir_details.get("med_holds", [])
    if med_holds:
        profile.med_holds = evaluate_ir_med_holds(med_holds, patient_data)
    
    # 4. Compute overall status
    profile.compute_overall_status()
    
    return profile
